data/quick_django_sample/main/urls.py
from django.urls import path

from . import views
from django.urls import path, re_path
from django.views.generic import TemplateView

urlpatterns = [
  # Part2
  path('', views.index, name='index'),
  path('temp', views.temp, name='temp'),
  path('list', views.list, name='list'),

  # Part3
  path('iftag', views.iftag, name='iftag'),
  path('yesno', views.yesno, name='yesno'),
  path('firstof', views.firstof, name='firstof'),
  path('forloop', views.forloop, name='forloop'),
  path('forempty', views.forempty, name='forempty'),
  path('fortag', views.fortag, name='fortag'),
  path('ifchanged', views.ifchanged, name='ifchanged'),
  path('regroup', views.regroup, name='regroup'),
  path('cycle', views.cycle, name='cycle'),
  path('escape', views.escape, name='escape'),
  path('temptag', views.temptag, name='temptag'),
  path('verbatim', views.verbatim, name='verbatim'),
  path('master', views.master, name='master'),
  path('include', views.include, name='include'),
  path('strformat', views.strformat, name='strformat'),
  path('slice', views.slice, name='slice'),
  path('lists', views.lists, name='lists'),
  path('date_time', views.date_time, name='date_time'),
  path('static', views.static, name='static'),

  # Part4
  path('filter', views.filter, name='filter'),
  path('exclude', views.exclude, name='exclude'),
  path('get', views.get, name='get'),
  path('filter_or', views.filter_or, name='filter_or'),
  path('filter_other', views.filter_other, name='filter_other'),
  path('groupby', views.groupby, name='groupby'),
  path('union', views.union, name='union'),
  path('raw', views.raw, name='raw'),  
  path('rel', views.rel, name='rel'),
  path('rel2', views.rel2, name='rel2'),

  # Part5
  path('route_param', views.route_param, name='route_param'),
  path('route_param/<int:id>', views.route_param, name='route_param'),

  # re_path('^route_param/(?P<id>[0-9]{2,3})$',
  #   views.route_param, name='route_param'),
  
  path('search/<path:keywd>', views.search, name='search'),
  path('req_query', views.req_query, name='req_query'),
  path('req_header', views.req_header, name='req_header'),
  path('req_redirect', views.req_redirect, name='req_redirect'),
  path('details/<int:id>', views.details, name='details'),
  path('res_notfound', views.res_notfound, name='res_notfound'),
  path('res_notfound', views.res_notfound, name='res_notfound'),
  path('res_header', views.res_header, name='res_header'),
  path('res_csv', views.res_csv, name='res_csv'),
  path('res_json', views.res_json, name='res_json'),
  path('res_file', views.res_file, name='res_file'),
  path('setcookie', views.setcookie, name='setcookie'),
  path('getcookie', views.getcookie, name='getcookie'),
  path('setsession', views.setsession, name='setsession'),
  path('getsession', views.getsession, name='getsession'),
  path('temp_view', views.MyTempView.as_view(), name='temp_view'),

  # path('temp_view', TemplateView.as_view(
  #   template_name='main/temp.html', extra_context={ 'msg': 'こんにちは、世界！！' }
  # ), name='temp_view'),

  # Part6
  path('form_input', views.form_input, name='form_input'),
  path('form_process', views.form_process, name='form_process'),
  path('upload_input', views.upload_input, name='upload_input'),
  path('upload_process', views.upload_process, name='upload_process'),

  # Part7
  path('crud_new', views.crud_new, name='crud_new'),
  path('crud_create', views.crud_create, name='crud_create'),
  path('crud_edit/<int:id>', views.crud_edit, name='crud_edit'),
  path('crud_update/<int:id>', views.crud_update, name='crud_update'),
  path('crud_show/<int:id>', views.crud_show, name='crud_show'),
  path('crud_delete/<int:id>', views.crud_delete, name='crud_delete'),
]

data/quick_django_sample/quick_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

data/quick_django_sample/main/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator, MinValueValidator

class Book(models.Model):
  isbn = models.CharField(
    verbose_name='ISBNコード',
    max_length=20,
    validators=[
      RegexValidator(
        r'^978-4-[0-9]{4}-[0-9]{4}-[0-9X]{1}$',
        message='ISBNコードは正しい形式で指定してください。')
    ]
  )
  title = models.CharField(
    verbose_name='書名',
    max_length=100
  )
  price = models.IntegerField(
    verbose_name='価格',
    default = 0,
    validators=[
      MinValueValidator(
        17,
        message='価格は正の整数で指定してください。'
      )
    ]
  )
  publisher = models.CharField(
    verbose_name='出版社',
    max_length=50,
    choices = [
      ('翔泳社', '翔泳社'),
      ('技術評論社', '技術評論社'),
      ('秀和システム', '秀和システム'),
      ('SBクリエイティブ', 'SBクリエイティブ'),
      ('日経BP', '日経BP'),
    ],
  )
  published = models.DateField(
      verbose_name='刊行日'
  )
  def __str__(self):
    return f'{self.title}({self.publisher}/{self.price}円)'

  # class Meta:
  #     ordering = ('published',)

  def get_absolute_url(self):
    return f'details/{self.id}'

class Review(models.Model):
  book = models.ForeignKey(Book, on_delete=models.CASCADE)
  name = models.CharField(
    verbose_name='名前',
    max_length=20
  )
  body = models.TextField(
    verbose_name='本文',
    max_length=255
  )
  def __str__(self):
    return f'{self.name}: {self.body[:10]}'

class Author(models.Model):
  books = models.ManyToManyField(Book)
  name = models.CharField(
    verbose_name='名前',
    max_length=20
  )
  address = models.CharField(
    verbose_name='住所',
    max_length=100
  )
  def __str__(self):
    return self.name

class User(models.Model):
  author = models.OneToOneField(Author, on_delete=models.CASCADE)    
  handle = models.CharField(
    verbose_name='ユーザー名',
    max_length=20
  )
  email = models.CharField(
    verbose_name='メールアドレス',
    max_length=100
  )
  def __str__(self):
    return self.handle

data/quick_django_sample/main/views.py
import csv
import random
import tempfile
import urllib.parse
from datetime import date
from datetime import datetime

from django.contrib import messages
from django.db.models import Q
from django.db.models import Count
from django.db.models.functions import Substr

from django.http import FileResponse
from django.http import Http404
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_GET
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from .forms import BookForm
from .forms import  BookModelForm
from .forms import UploadForm
from .models import Book

# Part2
def index(request):
  return HttpResponse('こんにちは、世界！')

def temp(request):
  context = {
    'msg' : 'こんにちは、世界！'
  }
  return render(request, 'main/temp.html', context)

def list(request):
  books = Book.objects.all() 
  return render(request, 'main/list.html', {
    'books': books
  })

# Part3
def iftag(request):
  return render(request, 'main/iftag.html', {
    'random': random.randint(0, 100)
  })

def yesno(request):
  return render(request, 'main/yesno.html', {
    'flag': True
  })

def firstof(request):
  return render(request, 'main/firstof.html', {
    # 'a': 'おはようございます！',
    # 'b': 'こんにちは！',
    # 'c': 'こんばんは！'
  })

def forloop(request):
  return render(request, 'main/forloop.html', {
    'weeks' : [ '月', '火', '水', '木', '金', '土', '日' ]
  })

def forempty(request):
  return render(request, 'main/forempty.html', {
    'members' : [ '鈴木三郎', '佐藤洋子', '山田次郎' ]
  })

def fortag(request):
  return render(request, 'main/fortag.html')

def ifchanged(request):
  return render(request, 'main/ifchanged.html', {
      'schedule': [
        (10, 'A企画反省会'),
        (10, 'B書籍脱稿'),
        (15, 'WINGS定例会議'),
        (30, 'C企画打ち合わせ'),
      ]
  })

def regroup(request):
  return render(request, 'main/regroup.html', {
    'members': [
      { 'name': '鈴木三郎', 'sex': '男', 'birth': '1980-12-23' },
      { 'name': '山田次郎', 'sex': '男', 'birth': '1978-10-13' },
      { 'name': '佐藤健司', 'sex': '男', 'birth': '1976-04-06' },
      { 'name': '山本花子', 'sex': '女', 'birth': '1981-07-28' },
      { 'name': '田中久美', 'sex': '女', 'birth': '1980-09-07' },
    ]
  })

def cycle(request):
  return render(request, 'main/cycle.html', {
    'members': [
      { 'name': '鈴木三郎', 'sex': '男', 'birth': '1980-12-23' },
      { 'name': '山田次郎', 'sex': '男', 'birth': '1978-10-13' },
      { 'name': '佐藤健司', 'sex': '男', 'birth': '1976-04-06' },
      { 'name': '山本花子', 'sex': '女', 'birth': '1981-07-28' },
      { 'name': '田中久美', 'sex': '女', 'birth': '1980-09-07' },
    ]
  })

def escape(request):
  return render(request, 'main/escape.html', {
    'msg': '''<img src="https://wings.msn.to/image/wings.jpg" title="ロゴ" />
      <p>WINGSへようこそ</p>'''
  })

def temptag(request):
  return render(request, 'main/temptag.html')

def verbatim(request):
  return render(request, 'main/verbatim.html')

def master(request):
  return render(request, 'main/master.html', {
    'msg' : 'こんにちは、世界！',
  })

def include(request):
  return render(request, 'main/include.html', {
    'name' : '鈴木',
    'current': datetime.now(), 
  })

def slice(request):
  return render(request, 'main/slice.html', {
      'data': [ 'い', 'ろ', 'は', 'に', 'ほ', 'へ' ]
  })

def strformat(request):
  return render(request, 'main/strformat.html', {
      'data1': None,
      'data2': 'WINGS\nWww INtegrated Guide on Server-architecture',
      'data3': 'https://wings.msn.to/',
      'data4': [ 'い', 'ろ', 'は', 'に', 'ほ', 'へ' ],
      'data5': 987.654,
      'data6': 'hello django'
  })

def lists(request):
  return render(request, 'main/lists.html', {
      'data': [ 'いろは歌', [ 'い', 'ろ', 'は', 'に', 'ほ', 'へ','と' ] ]
  })

def date_time(request):  
  return render(request, 'main/date_time.html', {
    'today': datetime.now()
  })

def static(request):  
  return render(request, 'main/static.html')

# Part4
def filter(request):
  books = Book.objects.filter(publisher='翔泳社')

  # AND条件
  # books = Book.objects.filter(publisher='翔泳社', price=2800)

  # 大小比較
  # books = Book.objects.filter(price__lt = 3000)

  # 部分一致
  # books = Book.objects.filter(title__contains = '独習')

  # 正規表現比較
  # books = Book.objects.filter(title__regex = r'[0-9]+')

  # NULL比較
  # books = Book.objects.filter(title__isnull = True)

  # 範囲比較
  # books = Book.objects.filter(published__range = 
  #   (date(2018, 1, 1), date(2018, 12, 31)))

  # 候補比較
  # books = Book.objects.filter(publisher__in = ['翔泳社', '技術評論社', '日経BP'])

  # 日付比較（年／月／日）
  # books = Book.objects.filter(published__year = 2019)
  # books = Book.objects.filter(published__year__lte = 2019)
  # books = Book.objects.filter(published__week_day__range = (2, 6))

  return render(request, 'main/book_list.html', {
    'books': books
  })

def filter_or(request):
  # books = Book.objects.filter(publisher='翔泳社') \
  #   .filter(price__gte = 2800)

  # Qオブジェクトの基本
  # books = Book.objects.filter(
  #   Q(publisher='翔泳社') | Q(price__gte = 2800))

  # より複雑な条件式
  books = Book.objects.filter(
    ~Q(publisher='翔泳社')
    & (Q(published__year = 2018) | Q(published__year = 2020))
  )
  return render(request, 'main/book_list.html', {
    'books': books
  })

def filter_other(request):
  # 出版社（昇順）／刊行日（降順）に
  books = Book.objects.order_by('publisher', '-published')

  # ランダムに
  # books = Book.objects.order_by('?')

  # 取得範囲の指定
  # books = Book.objects.order_by('-price')[2:5]

  # 取得列の制約
  # books = Book.objects.values('title', 'price')

  # 書名から最初の5文字だけを取り出す
  # books = Book.objects.values('price', short_title=Substr('title', 1, 5))
  # return HttpResponse(books[0]['short_title'])

  # リストとして取得
  # books = Book.objects.values_list('title', flat = True)
  # return HttpResponse(books[0])

  return render(request, 'main/book_list.html', {
    'books': books
  })

def exclude(request):
  books = Book.objects.exclude(publisher='翔泳社')
  return render(request, 'main/book_list.html', {
    'books': books
  })

def get(request):
  book = Book.objects.get(pk=1)
  return render(request, 'main/book_detail.html', {
    'book': book
  })  

def groupby(request):
  return render(request, 'main/groupby.html', {
    'groups': Book.objects.values('publisher')
      .annotate(pub_count=Count('publisher')).order_by('-pub_count')
  })

  # cnt = Book.objects.filter(publisher='翔泳社').count()
  # return HttpResponse(cnt)

  # flag = Book.objects.filter(publisher='翔泳社').exists()
  # return HttpResponse(flag)
  
def union(request):
  b1 = Book.objects.filter(publisher = '翔泳社')
  b2 = Book.objects.filter(publisher = '技術評論社')
  return render(request, 'main/book_list.html', {
    'books' : b1.union(b2)
  })

def raw(request):
  books = Book.objects.raw(
    'SELECT * FROM main_book WHERE publisher = %s', ['翔泳社'])
  return render(request, 'main/book_list.html', {
    'books': books
  })  

def rel(request):
  return render(request, 'main/rel.html', {
    'book' : Book.objects.get(pk=1)
  })

def rel2(request):
  return render(request, 'main/rel2.html', {
    'books' : Book.objects.all()
  })

# Part5
def route_param(request, id=1):
  return HttpResponse(f'id値：{id}')

def search(request, keywd):
  return HttpResponse(f'パラメーター：{keywd}')

def req_query(request):
  return HttpResponse(f'id値：{request.GET["id"]}')

def req_header(request):
  return HttpResponse(f'Use-Agent： {request.headers["User-Agent"]}')

def req_redirect(request):
  # return redirect('list')
  # return redirect('http://wings.msn.to/', permanent=True)
  # return redirect('route_param', id=10)

  # path = reverse('route_param', kwargs={ 'id': 1 })
  # return HttpResponse(path)
  
  book = Book.objects.get(pk=1)
  return redirect(book)

def details(request, id):
  return HttpResponse(f'id値：{id}')

def res_notfound(request):
  # try:
  #   book = Book.objects.get(pk=108)
  # except Book.DoesNotExist:
  #   raise Http404('指定の書籍情報が存在しません。')

  book = get_object_or_404(Book, pk=108)
  return render(request, 'main/book_detail.html', {
    'book': book
  })

def res_header(request):
  response = HttpResponse('<message>Hello, world!!</message>',
    content_type='text/xml')
  # response = HttpResponse('<message>Hello, world!!</message>')
  response['Content-Disposition'] = 'attachment; filename="hoge.xml"' 
  # response['Content-Type'] = 'text/xml'
  return response

def res_csv(request):
  response = HttpResponse(content_type='text/csv')
  response['Content-Disposition'] = 'attachment; filename="data.csv"'
  writer = csv.writer(response)
  writer.writerows([
    ['tyamada', '山田太郎', '30'],
    ['ksuzuki', '鈴木健司', '26'],
    ['itanaka', '田中一郎', '34']
  ])
  return response

def res_json(request):
  return JsonResponse({
    'title' : '独習Python',
    'price' : 3200,
    'publisher' : '翔泳社',
    'published' : date(2020, 6, 23) 
  })
  # return JsonResponse(['Python', 'Ruby', 'PHP'], safe = False)

def res_file(request):
  return FileResponse(open('c:/data/wings.png', 'rb'),
    as_attachment=True, filename='download.png')

def setcookie(request):
  response = HttpResponse(render(request, 'main/setcookie.html'))
  response.set_cookie('app_title',
    urllib.parse.quote('速習Django'), 60 * 60 * 24 * 30, samesite='Strict')
  # return response
  return redirect('http://wings.msn.to/')

def getcookie(request):
  app_title = urllib.parse.unquote(request.COOKIES['app_title']) \
    if 'app_title' in request.COOKIES else '－'
  return render(request, 'main/getcookie.html', {
    'app_title': app_title
  })

def setsession(request):
  request.session['app_title'] = '速習Django'
  return HttpResponse('セッションを保存しました。')

def getsession(request):
  title = request.session['app_title'] \
    if 'app_title' in request.session else '－' 
  return HttpResponse(title)

class MyTempView(TemplateView):
  template_name = 'main/temp.html'
  def get_context_data(self, **kwargs):

data/quick_django_sample/main/templates/main/book_list.html
{% extends 'main/layout.html' %}

{% block main %}
<table class="table">
  <thead>
  <tr>
    <th>ISBNコード</th><th>書名</th><th>価格</th><th>出版社</th><th>刊行日</th>
  </tr>
  </thead>
  <tbody>
  {% for b in books %}
  <tr>
    <td>{{ b.isbn }}</td>
    <td>{{ b.title }}</td>
    <!-- <td>{{ b.short_title }}</td> -->
    <td>{{ b.price }}</td>
    <td>{{ b.publisher }}</td>
    <td>{{ b.published|date:'DATE_FORMAT' }}</td>
  </tr>
  {% endfor %}
  </tbody>
  </table>
{{ data | unordered_list }}
{% endblock %}

data/quick_django_sample/main/templates/main/crud_new.html
{% extends 'main/layout.html' %}

{% block main %}
{% for message in messages %}
  <div class="alert alert-success">{{message}}</div>
{% endfor %}
<ul>
  {% for field in form %}
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
  {% endfor %}
</ul>
<form action="./crud_create" method="post" novalidate>
  {% csrf_token %}
  {% for field in form %}
    <div class="pl-2">
      {{ field.label_tag }}<br />
      {{ field }}
      {{ field.errors | yesno:'*,' }}
    </div> 
  {% endfor %}
  <input type="submit" value="送信" />
</form>
{% endblock %}

data/quick_django_sample/main/templates/main/cycle.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<title>速習 Django</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
</head>
<body>
<table class="table">
  <thead>
    <th>名前</th><th>性別</th><th>誕生日</th>
  </thead>
  {% for m in members %}
  <tr style="background-color: {% cycle 'skyblue' 'aquamarine' 'lightgreen' %}">
    <td>{{ m.name }}</td>
    <td>{{ m.sex }}</td>
    <td>{{ m.birth }}</td>
  </tr>
  <!-- 
  <tr>
    <td style="background-color: {% cycle 'skyblue' 'aquamarine' 'lightgreen' as bg %}">{{ m.name }}</td>
    <td style="background-color: {{bg}}">{{ m.sex }}</td>
    <td  style="background-color: {{bg}}">{{ m.birth }}</td>
  </tr>
   -->
  {% endfor %}
  </table>
</body>
</html>

data/quick_django_sample/main/templates/main/date_time.html
{% extends 'main/layout.html' %}

{% block main %}
<ul>
  <li>{{ today|date:'Y年m月d日 H:i' }}</li>
  <li>{{ today|time:'H時i分s秒' }}</li>
  <li>{{ today|date:'SHORT_DATE_FORMAT' }}</li>
  <li>{{ today|date:'DATE_FORMAT' }}</li>
  <li>{{ today|date:'TIME_FORMAT' }}</li>
</ul>
{{ data | unordered_list }}
{% endblock %}

data/quick_django_sample/main/templates/main/firstof.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<title>速習 Django</title>
</head>
<body>
{% firstof a b c 'さようなら' %}

<!-- 
{% if a %}
  {{ a }}
{% elif b %}
  {{ b }}
{% elif c %}
  {{ c }}
{% else %}
  さようなら
{% endif %}
 -->
</body>
</html>

data/quick_django_sample/main/templates/main/forempty.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<title>速習 Django</title>
</head>
<body>
{% for m in members %}
  <li>{{ m }}</li>
{% empty %}
  <p>データは存在しません。</p>
{% endfor %}  
</body>
</html>    

data/quick_django_sample/main/templates/main/forloop.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
<table class="table">
<thead>
<tr>
  <th>値</th>
  <th>counter</th>
  <th>counter0</th>
  <th>rev</th>
  <th>rev0</th>
  <th>first</th>
  <th>last</th>
</tr>
</thead>
<tbody>
{% for week in weeks %}
  <tr>
  <td>{{ week }}</td>
  <td>{{ forloop.counter }}</td>
  <td>{{ forloop.counter0 }}</td>
  <td>{{ forloop.revcounter }}</td>
  <td>{{ forloop.revcounter0 }}</td>
  <td>{{ forloop.first }}</td>
  <td>{{ forloop.last }}</td>
  </tr>
{% endfor %}
</tbody>
</table>
</body>
</html>

data/quick_django_sample/main/templates/main/getcookie.html
{% extends 'main/layout.html' %}

{% block main %}
<p>{{ app_title }}</p>
{% endblock %}

data/quick_django_sample/main/templates/main/include.html
{% extends 'main/layout.html' %}

{% block main %}
  {% include 'main/include_sub.html' with fmt='H:i:s' %}
{% endblock %}

data/quick_django_sample/main/templates/main/lists.html
{% extends 'main/layout.html' %}

{% block main %}
<ul>
  <li>{{ data | length }}</li>
  <li>{{ data | first }}</li>
  <li>{{ data | last }}</li>
  <li>{{ data | random }}</li>
</ul>
{{ data | unordered_list }}
{% endblock %}

data/quick_django_sample/main/templates/main/master.html
{% extends 'main/layout.html' %}

{% block title %}テンプレートの継承{% endblock %}

{% block main %}
<p>{{ msg }}</p>
{% endblock %}

data/quick_django_sample/main/templates/main/rel.html
{% extends 'main/layout.html' %}

{% block main %}
<h3>「{{book.title}}」のレビュー</h3>
<hr />
<ul>
{% for rev in book.review_set.all %}
  <li>{{ rev.body }}（{{ rev.name }}）</li>
{% endfor %}
</ul>
{% endblock %}  

data/quick_django_sample/main/templates/main/temp.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<title>速習 Django</title>
</head>
<body>
<p>{{ msg }}</p>
</body>
</html>

data/quick_django_sample/main/templates/main/yesno.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<title>速習 Django</title>
</head>
<body>
{{ flag | yesno:'OK,NG,Unknown' }}
</body>
</html>